version: '3'

networks:
  my-network:
    driver: bridge

services:
  app:
    build: .
    ports:
      - "3333:3333"
    networks:
      - my-network
    environment:
      DATABASE_URL: "file:./dev.db"
      GITHUB_CLIENT_ID: "bce6d84e17efad8b028c"
      GITHUB_CLIENT_SECRET: "32317fc1241ac5545778882219a6f6afd67e2e62"
