version: '3'

services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: "file:./dev.db"
      GITHUB_CLIENT_ID: "bce6d84e17efad8b028c"
      GITHUB_CLIENT_SECRET: "32317fc1241ac5545778882219a6f6afd67e2e62"
